# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 21, 22, 31, 227799, tzinfo=utc)),
        ),
    ]
