# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20151218_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 17, 21, 56, 22, 546201, tzinfo=utc)),
        ),
    ]
